# Generated by Django 4.2.5 on 2023-11-02 00:32

import api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('ord', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter the ORD in ORD-XXXXX-XXXX format.', regex='^ORD-[0-9]{6}-[0-9A-Z]{4}$')])),
                ('project_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Headsup', 'Headsup'), ('Programming', 'Programming'), ('Changes', 'Changes'), ('Live', 'Live'), ('LiveChange', 'Live Changes'), ('Closed', 'Closed')], default='Headsup', max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('region', models.CharField(blank=True, choices=[('APAC', 'APAC'), ('EMEA', 'EMEA'), ('NA', 'NA')], max_length=10)),
                ('pid', models.CharField(blank=True, max_length=20)),
                ('platform', models.CharField(choices=[('Decipher', 'Decipher'), ('CMIX', 'CMIX'), ('Confirmit', 'Confirmit')], default='Decipher', max_length=15)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True, max_length=255)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_header', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, max_length=255, null=True)),
                ('update_type', models.CharField(choices=[('update', 'Update only'), ('scripting', 'Started Scripting'), ('testlinksent', 'Test Link Sent'), ('settolive', 'Set to Live'), ('settolivechange', 'Change to Live Changes'), ('paused', 'Paused'), ('toclosed', 'Set to Closed'), ('reopened', 'Re-open Project'), ('created', 'Project created'), ('edited', 'Project details edited')], default='update', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project', to_field='code')),
            ],
        ),
    ]
