# Generated by Django 4.2.5 on 2023-10-10 13:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('ord', models.CharField(max_length=15, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('status', models.CharField(default='Headsup', max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('region', models.CharField(blank=True, max_length=10)),
                ('pid', models.CharField(blank=True, max_length=20)),
                ('platform', models.CharField(default='Decipher', max_length=15)),
                ('markets', models.CharField(blank=True, max_length=50)),
                ('hours', models.CharField(blank=True, max_length=20)),
                ('eta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
