# Generated by Django 4.2.5 on 2023-10-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord', models.CharField(max_length=15, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('status', models.CharField(default='Headsup', max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
