# Generated by Django 4.2.5 on 2023-10-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_eta_project_hours_project_markets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pid',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
